# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Takeshi Morita
ja_title: 森田 武史
email: t_morita [at] ae.keio.ac.jp
description: Under Construction

# Build settings
markdown: kramdown

gems:           ['jekyll-paginate', 'jekyll-multiple-languages']
languages:          ['en', 'ja']
language_default:   'en'