# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MORITA Takeshi
ja_title: 森田 武史
email: morita [at] it.aoyama.ac.jp
description: MORITA Takeshi Web Site

# Build settings
markdown: kramdown
